name = "lune_utils/roblox_apis"
version = "0.1.0"
authors = ["0xJWLabs <hi@0xjwlabs.dev>"]
license = "MIT"

includes = ["src/**/*", "pesde.toml", "LICENSE"]

[engines]
lune = "^0.9"

[target]
environment = "lune"
lib = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
